### ISSUE TITLE
unable to verify the first certificate

### ISSUE THREAD

**Issue by detiam** [Sak32009/SteamLauncher#124]
previous version works fin.
![image](https://user-images.githubusercontent.com/44510779/161403640-95fd904c-b2d6-41e4-a83b-be2484a3cc39.png)
find out that this is because steam++ ([SteamTools](https://github.com/BeyondDimension/SteamTools)) modified steam's domains to local in order to make steam accessible in where I live. I already installed certificate in systemwide so real steam client is working with steam++, any workround or could you fix it?

**Comment by Sak32009** [comment]
I didn't quite understand what exactly steamTools does, is it possible to explain it better?

**Comment by Sak32009** [comment]
Fixed. Please update to v0.1.1 :)

**Comment by detiam** [comment]
thanks!

**Comment by detiam** [comment]
![Honeycam 2022-04-03 21-11-04](https://user-images.githubusercontent.com/44510779/161429837-f95fe0d0-0056-49fd-b1d5-11e3a4997be7.gif)
It still happen, can I provide something like logs to help?

**Comment by Sak32009** [comment]
Go to the SteamLauncher installation folder, replace app.asar with the attached one in the "resources" folder.

Change app.txt to app.asar before replace.

Let me know

[app.txt](https://github.com/Sak32009/SteamLauncher/files/8404654/app.txt)
.

**Comment by detiam** [comment]
after replace it works now

**Comment by Sak32009** [comment]
Perfect :)
